# site
title: Melissa
baseurl: "/index"
url: "https://m3lissacox.github.io/"
favicon: "/assets/ico.png"
g_analytics: 

# bio
header: Melissa Cox
desc: >
  Welcome to my website! 
  Here is where I accumulate my stash of graphics. Created predominantly with Photoshop and Illustrator.

# posts
date_format: "%B %Y"

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

theme: fry